#!/usr/bin/env bash
# Lightweight static checks for the single-file macOS client.
set -euo pipefail

cd "$(dirname "$0")/.."

src="mac/codex-dictate.swift"
agents="mac/install-agents.sh"
readme="mac/README.md"
build="mac/build.sh"
proxy="proxy/main.go"

grep -q 'CODEX_DICTATE_INPUT_DEVICE' "$src"
grep -q 'CODEX_DICTATE_FALLBACK_INPUT_DEVICE' "$src"
grep -q 'CODEX_DICTATE_SILENCE_RMS_DB' "$src"
grep -q 'CODEX_DICTATE_MAX_RECORDING_SECONDS' "$src"
grep -q 'CODEX_DICTATE_TRANSCRIBE_TIMEOUT' "$src"
grep -q 'CODEX_DICTATE_SHOW_UI' "$src"
grep -q 'chooseAudio' "$src"
grep -q 'wavMetrics' "$src"
grep -q 'already recording; stopping' "$src"
grep -q 'max recording duration reached' "$src"
grep -q 'sox did not terminate; killing' "$src"
grep -q 'bad proxy response status=' "$src"
grep -q 'bodyPreview' "$src"
grep -q 'AXIsProcessTrusted' "$src"
grep -q 'transcribed chars=' "$src"
grep -q 'left transcript on clipboard' "$src"
grep -q -- '-t", "coreaudio"' "$src"
grep -q 'enum PillState' "$src"
grep -q 'final class StatusPillView' "$src"
grep -q 'final class StatusPillPanel' "$src"
grep -q 'final class StatusPillController' "$src"
grep -q 'canBecomeKey' "$src"
grep -q 'statusPillController' "$src"
grep -q 'NSPanel' "$src"
grep -q 'NSScreen' "$src"
grep -Eq '\.statusBar|statusBar' "$src"
grep -q 'ignoresMouseEvents = true' "$src"
grep -q 'collectionBehavior' "$src"
grep -q '.stationary' "$src"
grep -q '.ignoresCycle' "$src"
grep -q 'showPill(.recording)' "$src"
grep -q 'showPill(.transcribing)' "$src"
grep -q 'hidePillSoon' "$src"
grep -q 'CODEX_DICTATE_FALLBACK_INPUT_DEVICE' "$agents"
grep -q 'CODEX_DICTATE_INPUT_DEVICE' "$agents"
grep -q 'CODEX_DICTATE_FALLBACK_INPUT_DEVICE' "$readme"
grep -q 'CODEX_DICTATE_INPUT_DEVICE' "$readme"
grep -q 'CODEX_DICTATE_SHOW_UI' "$readme"
grep -q 'bottom-center' "$readme"
grep -q 'Status pill' "$readme"
grep -q 'CODEX_DICTATE_CODESIGN_IDENTITY' "$build"
grep -q -- '--identifier io.codexdictate.client' "$build"
grep -q 'CODEX_DICTATE_CODESIGN_IDENTITY' "$readme"
grep -q 'CODEX_DICTATE_BROWSER_UA' "$proxy"
grep -q 'Chrome/149' "$proxy"
grep -q 'upstream status=' "$proxy"
